
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Moshiur
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        error_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close_lbl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        error_lbl = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_lbl.setBackground(new java.awt.Color(255, 255, 255));
        close_lbl.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        close_lbl.setForeground(new java.awt.Color(255, 0, 0));
        close_lbl.setText("X");
        close_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_lblActionPerformed(evt);
            }
        });
        getContentPane().add(close_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        error_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error_lbl.setForeground(new java.awt.Color(255, 0, 0));
        error_lbl.setText("[ X ] Incorrect Username or Password");
        getContentPane().add(error_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        user_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_txt.setText("Enter Username");
        user_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_txtFocusLost(evt);
            }
        });
        getContentPane().add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 350, 40));

        pass_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_txt.setText("Enter Password");
        pass_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_txtFocusLost(evt);
            }
        });
        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        getContentPane().add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 350, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/University-Portal.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txtFocusGained
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(user_txt.getText().equals("Enter Username"))
        {
            user_txt.setText("");
            user_txt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_user_txtFocusGained

    private void user_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txtFocusLost
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(user_txt.getText().equals(""))
        {
            user_txt.setText("Enter Username");
            user_txt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_user_txtFocusLost

    private void pass_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusGained
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(pass_txt.getText().equals("Enter Password"))
        {
            pass_txt.setText("");
            pass_txt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_pass_txtFocusGained

    private void pass_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusLost
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(pass_txt.getText().equals(""))
        {
            pass_txt.setText("Enter Password");
            pass_txt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_pass_txtFocusLost

    private void close_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_lblActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null,"Do you really want to exit !","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_close_lblActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(user_txt.getText().equals("hridoy") && pass_txt.getText().equals("admin"))
        {
            setVisible(false);
            new Splash_screen().setVisible(true);
        }
        else
            error_lbl.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            pass_txt.setEchoChar((char)0);
        }
        else
        {
            pass_txt.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_lbl;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
